version: '4'
name: 'devanddeliver.dev_app'
services:
  redis:
    container_name: devanddeliver.dev_redis
    restart: always
    image: redis:alpine
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=devanddeliver
      - REDIS_USER=devanddeliver
      - REDIS_DB=0
    volumes:
      - devanddeliver.dev_redis-data:/data
  app:
    container_name: devanddeliver.dev_app
    environment:
      - PORT=8080
    restart: always
    depends_on:
      - redis
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '8080:8080'

volumes:
  devanddeliver.dev_redis-data:
    name: devanddeliver.dev_redis-data
