version: '4'
name: 'dawid_szemborowski'
services:
  redis:
    container_name: swapi-graphql.dev_redis
    restart: always
    image: redis:alpine
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=swapi-graphql
      - REDIS_USER=swapi-graphql
      - REDIS_DB=0
    volumes:
      - swapi-graphql.dev_redis-data:/data
  app:
    container_name: swapi-graphql.dev_app
    restart: always
    environment:
      - PORT=8080
      - REDIS_URL=redis://redis:6379
      - SWAPI_HOST=https://swapi.dev/api
    depends_on:
      - redis
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '8080:8080'

volumes:
  swapi-graphql.dev_redis-data:
    name: swapi-graphql.dev_redis-data
